### PR TITLE
More renaming, and UI readme addition

### PR DESCRIPTION
**Pull request by blobjim**
- Renamed BaseStation, BaseServer, and MainWindow to EntryPoint, Server, and UserInterface respectively. 
- Added required gstreamer .dll file list to UserInterface readme file.
- Renamed readme.md files to README.md

### CODE REVIEW

**Comment by blobjim** [comment]
OK, I think I've cleaned up most of the weird things in the repo

**Comment by blobjim** [comment]
lmao still makin' commits 🕺

**Comment by Obbay2** [comment]
You're right that isn't what GitHub is supposed to be for, I'm just thinking that people are lazy and won't want to set up the files, or won't know how. In theory the minimum set of gstreamer libraries should be small and compact enough that we can break this rule. But since I'm not making this issue a part of this pull request, I will approve your changes :).

**Comment by blobjim** [comment]
Yay!

**Pull request merged**
